[workspace]
members = ["crates/*"]

[profile.dev]
incremental = false # https://github.com/rust-lang/rust/issues/91807

[profile.test]
incremental = false # https://github.com/rust-lang/rust/issues/91807
