name: Install Wasmtime
description: Install Wasmtime
runs:
  using: composite
  steps:
    - name: Install Wasmtime
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      run: |
        curl https://wasmtime.dev/install.sh -sSf | bash
        WASMTIME_HOME="$HOME/.wasmtime"
        echo "WASMTIME_HOME=$WASMTIME_HOME" >> $GITHUB_ENV
        echo "$WASMTIME_HOME/bin" >> $GITHUB_PATH
      shell: bash
    - name: Install Wasmtime
      if: ${{ runner.os == 'Windows' && runner.arch == 'X64' }}
      run: |
        $Uri = 'https://github.com/bytecodealliance/wasmtime/releases/download/dev/wasmtime-dev-x86_64-windows.msi'
        $MsiFile = 'wasmtime.msi'
        $LogFile = 'wasmtime-install.log'
        Invoke-WebRequest -Uri $Uri -OutFile $MsiFile
        $MsiFile = Get-Item -Path .\$MsiFile
        $Process = Start-Process -FilePath msiexec.exe -ArgumentList "/i $($MsiFile.FullName) /qn /norestart /l*v $LogFile" -Wait -NoNewWindow -PassThru
        $Process | Select-Object -Property Id, ProcessName, ExitCode
        Get-Content -Path .\$LogFile
        "$($env:ProgramFiles)\Wasmtime\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh
